### ISSUE TITLE
Start logger with dict in addition to yaml or kwargs

### ISSUE THREAD

**Issue by bmight** [RyanMillerC/clogging#7]
Add the ability to start a logger with a dict of the logger parameters in addition to yaml file or kwargs.

Suggest adding *args to the start function and ConLog class. Then check if it args has a dict. Set the dict first and allow kwargs to overwrite settings in the dict.

**Comment by RyanMillerC** [comment]
Technically this should be trivial to implement. I am concerned that the use case for this enhancement is niche and that adding this option will further clutter the documentation for **start**, which could make the module harder to understand at first glance.

**Comment by bmight** [comment]
After some thought, this could cause some confusion to the documentation. I will mark it as won't fix and close the issue.
